#!/bin/bash

# Taco Java server launch script.
# Copyright (C) 2014-2015 Graham Bell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

JARFILE=`dirname $0`/../target/taco-0.0-jar-with-dependencies.jar

# Use -classpath rather than -jar so that any existing CLASSPATH can
# be included.

java \
    -classpath ${JARFILE}${CLASSPATH:+:$CLASSPATH} \
    io.github.grahambell.taco.TacoServer
